[package]
name = "rover-gui"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[[bin]]

name="navigation"
path="../src/navigation.rs"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.conrod]
git = "https://github.com/pistondevelopers/conrod"

[dependencies.ffmpeg]
git = "https://github.com/tedsta/rust-ffmpeg"
features = ["codec", "device", "filter", "format", "postprocessing", "software-resampling", "software-scaling"]
default-features = false

[dependencies]

time = "0.1.*"
sdl2 = "*"
piston = "0.1.4"
piston2d-graphics = "0.1.4"
piston2d-opengl_graphics = "0.1.0"
image = "*"