[package]
name = "rover-gui"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[[bin]]

name="telemetry"
path="../src/telemetry.rs"

[dependencies]

time = "0.1.*"
piston_window = "0.43.0"
piston2d-graphics = "0.16.0"
conrod = "0.34.0"
