[package]
name = "rover-gui"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[[bin]]

name="telemetry"
path="../src/telemetry.rs"

[dependencies]

time = "0.1.*"
sdl2 = "0.5.0"
pistoncore-sdl2_window = "0.4.0"
piston = "0.3.0"
piston2d-graphics = "0.4.0"
piston2d-opengl_graphics = "0.4.0"
conrod = "0.5.0"
